server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: br.com.kafka.producer.utils.MessageSerializer